name: Build JSON

on:
  push:
    branches: 
      - master
  pull_request:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16.x'
      
      - name: Run build
        run: npm run build
      
      - name: Commit & Push
        run: |
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automated build"
            git push
          fi
